FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir mlflow==2.19.0 psycopg2-binary==2.9.10 boto3==1.35.99

COPY scripts ./scripts
RUN chmod +x /app/scripts/mlflow-entrypoint.sh

ENTRYPOINT ["/app/scripts/mlflow-entrypoint.sh"]
