apiVersion: batch/v1
kind: CronJob
metadata:
  name: mms-rollout-controller
  namespace: mms
spec:
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ghcr-pull
