apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mms
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - minio.yaml
  - mlflow.yaml
  - model-serve.yaml
images:
  - name: ghcr.io/your-org/mealie-model-serve-mlflow
    newName: ghcr.io/your-org/mealie-model-serve-mlflow
    newTag: latest
  - name: ghcr.io/your-org/mealie-model-serve-api
    newName: ghcr.io/your-org/mealie-model-serve-api
    newTag: latest
